config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: "omniauth_callbacks" }
  
  get '/comparisons/new', to: 'comparisons#new'
  get '/comparisons/show', to: 'comparisons#show'

  scope '/comparisons' do
    resources :maps, only: [:index]
  end

  root to: 'sessions#new'

  get '/how-it-works', to: 'about#show' 
  get '/api-info', to: 'about#api_info' 

  post '/send-email', to: 'email#send_email'
    
  namespace :api do
    namespace :v1 do
      resources :comparisons, only: [:index]
    end
  end

end

app/models/address.rb
class Address 
  include ActiveModel::Validations

  attr_accessor :address, :city

  validates :city, 
            inclusion: { in: ["Denver"], message: "must be located in Denver." }, 
            if: 'address.present?'
  validates :address, presence: { message: " cannot be blank." }, on: [:new, :show] 

  def initialize(address)
    @address = address
  end

  def city
    Geocoder.search(@address).first.city
  end

  def address_in_denver?
    Geocoder.search(@address).first.city == "Denver"
  end

end

app/models/art_gallery.rb
class ArtGallery < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
end

app/models/b_cycle.rb
class BCycle < ActiveRecord::Base
  validates :address, uniqueness: true, presence: true

  geocoded_by :address
  after_validation :geocode
end

app/models/bar.rb
class Bar < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
end

app/models/bus_stop.rb
class BusStop < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
end

app/models/coffee_shop.rb
class CoffeeShop < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
end

app/models/crime.rb
require 'date'

class Crime < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude

#  def self.current_year
#    Crime.where(date: full_year )
#  end
#
#  def full_year
#    (Date.today - 1.year)..Date.today 
#  end
end

app/models/grocery_store.rb
class GroceryStore < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
end

app/models/hardware_store.rb
class HardwareStore < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
end

app/models/library.rb
class Library < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
end

app/models/liquor_store.rb
class LiquorStore < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
end

app/models/live_music.rb
class LiveMusic < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
end

app/models/museum.rb
class Museum < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
end

app/models/park.rb
class Park < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude
end

app/models/pharmacy.rb
class Pharmacy < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
end

app/models/theater.rb
class Theater < ActiveRecord::Base
  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  
  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first

    if user
      return user
    else
      registered_user = User.where(:email => auth.uid + "@twitter.com").first
      if registered_user
        return registered_user
      else
        user = User.create( name:auth.extra.raw_info.name,
                            provider:auth.provider,
                            uid:auth.uid,
                            email:auth.uid+"@twitter.com",
                            password:Devise.friendly_token[0,20],
                          )
      end
    end
  end
end

app/models/venue.rb
module Venue
  def self.categories
  {
    "Park": "4bf58dd8d48988d163941735", 
    "GroceryStore": "4bf58dd8d48988d118951735", 
    "Library": "4bf58dd8d48988d12f941735", 
    "Restaurant": "4d4b7105d754a06374d81259", 
    "Bar": "4bf58dd8d48988d11b941735,4bf58dd8d48988d121941735,4bf58dd8d48988d118941735", 
    "CoffeeShop": "4bf58dd8d48988d1e0931735", 
    "Museum": "4bf58dd8d48988d181941735", 
    "LiquorStore": "4bf58dd8d48988d186941735", 
    "Pharmacy": "4bf58dd8d48988d10f951735", 
    "BusStop": "52f2ab2ebcbc57f1066b8b4f", 
    "LightRailStop": "52f2ab2ebcbc57f1066b8b4f", 
    "Theater": "4bf58dd8d48988d137941735,4bf58dd8d48988d135941735,4bf58dd8d48988d1ac941735", 
    "Movie": "4bf58dd8d48988d17f941735", 
    "LiveMusic": "4bf58dd8d48988d1e5931735", 
    "ArtGallery": "4bf58dd8d48988d1e2931735", 
    "HardwareStore": "4bf58dd8d48988d112951735"
  }
  end
end

app/controllers/api/v1/comparisons_controller.rb
class Api::V1::ComparisonsController < Api::V1::BaseController
  respond_to :json
  
  def index
    first_address = Address.new(params["first_address"])
    second_address = Address.new(params["second_address"])
    if first_address.invalid?
      render json: { errors: first_address.errors.full_messages }, status: 422 
    elsif Query.new(params).queries.nil? 
      render json: { errors: first_address.errors.full_messages }, status: 422 
    else
      @results = Query.new(params).api_start
      render json: JSON.pretty_generate(@results)
    end
  end

end

app/controllers/comparisons_controller.rb
class ComparisonsController < ApplicationController
  include GoogleMaps
  respond_to :json, :xml

#  before_filter :authenticate 
  attr_reader :first_address, :second_address

  def new
  end
  
  def show
    @first_address = Address.new(params["first_address"])
    @second_address = Address.new(params["second_address"])
    if @first_address.invalid? 
      flash[:notice] = @first_address.errors.full_messages
      render :new
    elsif @second_address.invalid?
      flash[:notice] = @second_address.errors.full_messages
      render :new
    elsif Query.new(params).queries.nil? 
      flash[:notice] = "You must choose at least one criteria for your comparison."
      redirect_to comparisons_new_path(request.params)
    else
      @queries = params["query"].keys
      @results = Query.new(params).start
    end
  end

  private

    def invalid_address?
      @first_address.invalid? || @second_address.invalid?
    end

end

app/views/comparisons/_conditional_results.html.erb
<tbody>
  <tr>
    <% if result.class == Crime %>
      <td><%= result.offense_type.formatted %></td>
      <td><%= result.date.to_date %></td>
    <% elsif result.respond_to?(:name) %>
      <td><%= result.name %></td>
      <!-- <td><%#= result.name %></td> ADD this functionality later -->
      <td><%= Geocoder::Calculations.distance_between(result.address, address).round(2) %></td>
    <% else %>
      <td><%= result["name"] %></td>
      <td class="location-distance">
      <% r = Geocoder::Calculations.distance_between(result["location"]["formattedAddress"].join, address).round(2) %>
        <% if !r.nan? %>
          <%= r %>
        <% end %>
      </td>        
    <% end %>
  </tr>
</tbody>

app/views/comparisons/new.html.erb
<div class="row wrapper small-12 small-centered query-box">
  <div class="small-12 small-centered columns comparison-container">
    <div class="row">
      <%= form_tag(comparisons_show_path, method: "get") do %>
      <div class="small-6 columns">
        <%= label_tag :first_address, nil, class: "address-label" %>
        <%= text_field_tag :first_address, params["first_address"], placeholder: "123 First Address St Denver, CO 80206", required: true %>
        <input type="checkbox" name="poptars" id="poptartsyes">
      </div>
      <div class="small-6 columns">
        <%= label_tag :second_address, nil, class: "address-label" %>
        <%= text_field_tag :second_address, params["second_address"], placeholder: "456 Second Address St Denver, CO 80218", required: true %>
      </div>
      <div class="row">
        <div class="large-12 columns">
          <ul class="button-group">
            <h3>Choose what you want in your neighborhood</h3>
            <li><a href="javascript:void(0)" class="button category-button general">General</a></li>
            <li><a class="button category-button convenience">Convenience
              <i class="fi-compass category-icon"></i></a>
            </li>
            <li><a class="button category-button things-to-do">Things To Do
              <i class="fi-ticket category-icon"></i></a>
            </li>
            <li><a class="button category-button food-and-drink">Food & Drink
              <i class="fi-star category-icon"></i></a>
            </li>
            <li><a class="button category-button transportation">Transportation
              <i class="fi-map category-icon"></i></a>
            </li>
          </ul>
        </div>
      </div>

      <!--convenience-group -->
      <div class="convenience-group criteria-group small-8 small-centered columns">
        <div class="category-checkbox small-centered columns">
          <div class="center">
            <input type="checkbox" name="query[liquor_stores]" id="query_liquor_stores">
            <label for="query_liquor_stores">LIQUOR STORES</label>
          </div>
        </div>

        <div class="category-checkbox small-centered columns">
          <div class="center">
            <input type="checkbox" name="query[grocery_stores]" id="query_grocery_stores">
            <label for="query_grocery_stores">GROCERY STORES</label>
          </div>
        </div>
        
        <div class="category-checkbox small-centered columns">
          <div class="center">
            <input type="checkbox" name="query[pharmacies]" id="query_pharmacies">
            <label for="query_pharmacies">PHARMACIES</label>
          </div>
        </div>

        <div class="category-checkbox small-centered columns">
          <div class="center">
            <input type="checkbox" name="query[hardware_stores]" id="query_hardware_stores">
            <label for="query_hardware_stores">HARDWARE STORES</label>
          </div>
        </div>

        <div class="category-checkbox small-centered columns">
          <div class="center">
            <input type="checkbox" name="query[libraries]" id="query_libraries">
            <label for="query_libraries">LIBRARIES</label>
          </div>
        </div>
      </div> 
    
      <!--general-group -->
      <div class="general-group criteria-group small-8 small-centered columns">
        <div class="category-checkbox small-centered columns">
          <div class="center ">
            <input type="checkbox" name="query[crimes]" id="query_crimes">
            <label for="query_crimes">SAFETY </label>
          </div>
        </div>
        
        <div class="category-checkbox small-centered columns">
          <div class="center ">
            <input type="checkbox" name="query[parks]" id="query_parks">
            <label for="query_parks">PARKS</label>
          </div>
        </div>
      </div> 
    
      <!--things-to-do-group -->
      <div class="things-to-do-group criteria-group small-8 small-centered columns">
        <div class="category-checkbox small-centered columns">
          <div class="center">
            <input type="checkbox" name="query[theaters]" id="query_theaters">
            <label for="query_theaters">THEATERS</label>
          </div>
        </div>
      
        <div class="category-checkbox small-centered columns">
          <div class="center">
            <input type="checkbox" name="query[movies]" id="query_movies">
            <label for="query_movies">MOVIES</label>
          </div>
        </div>

        <div class="category-checkbox small-centered columns">
          <div class="center">
            <input type="checkbox" name="query[museums]" id="query_museums">
            <label for="query_museums">MUSEUMS</label>
          </div>
        </div>

        <div class="category-checkbox small-centered columns">
          <div class="center">
            <input type="checkbox" name="query[art_galleries]" id="query_art_galleries">
            <label for="query_art_galleries">ART GALLERIES</label>
          </div>
        </div>
      </div> 
      
      <!--transportation-group -->
      <div class="transportation-group criteria-group small-8 small-centered columns">
        <div class="category-checkbox small-centered columns">
          <div class="center">
            <input type="checkbox" name="query[bcycle_stations]" id="query_bcycle_stations">
            <label for="query_bcycle_stations">B-CYCLE STATIONS</label>
          </div>
        </div>

        <div class="category-checkbox small-centered columns">
          <div class="center">
            <input type="checkbox" name="query[bus_stops]" id="query_bus_stops">
            <label for="query_bus_stops">BUS STOPS</label>
          </div>
        </div>

        <div class="category-checkbox small-centered columns">
          <div class="center">
            <input type="checkbox" name="query[light_rail_stops]" id="query_light_rail_stops">
            <label for="query_light_rail_stops">LIGHT RAIL STOPS</label>
          </div>
        </div>
      </div> 

      <div class="food-and-drink-group criteria-group small-8 small-centered columns">
        
        <div class="category-checkbox small-centered columns">
          <div class="center">
            <input type="checkbox" name="query[restaurants]" id="query_restaurants">
            <label for="query_restaurants">RESTAURANTS</label>
          </div>
        </div>

        <div class="category-checkbox small-centered columns">
          <div class="center">
            <input type="checkbox" name="query[bars]" id="query_bars">
            <label for="query_bars">BARS</label>
          </div>
        </div>

        <div class="category-checkbox small-centered columns">
          <div class="center">
            <input type="checkbox" name="query[coffee_shops]" id="query_coffee_shops">
            <label for="query_coffee_shops">COFFEE SHOPS</label>
          </div>
        </div>
      </div>
    </div>
    
    <div class="radius">
      <h4>Search within 
        <%= select_tag :radius, options_for_select(['0.1', '0.2', '0.3', '0.4', '0.5', '0.8', '1.0', '1.5', '2.0', '5.0'], '0.3'), class: "radius-dropdown small-1 small-centered" %> miles of each address
      </h4>
    </div>
        <%= submit_tag "COMPARE", id: "compare", class: "button radius round" %>
      <% end %>
    </div>
  </div>
</div>

app/views/comparisons/show.html.erb
<div class="show-container">
  <h3 class="distance-title large-6 large-centered columns">
  <span>Within <span class="radius-standout"><%="#{params['radius']} " %></span>miles of each address there are: </span>
  </h3>

  <%= image_tag @street_view %>
  <h2 class="first-address large-6 columns"><%= @first_address.address  %></h2>
  <h2 class="second-address large-6 columns"><%= @second_address.address %></h2>

  <div class="first-address-results large-6 columns">
    <% @queries.each do |query| %>
      <div class="results">
        <h4 class="small-4 small-centered columns">
          <a href="#" class="<%= "first-address-" + query %> criteria-details">
          <%= "#{(@results.send(query.to_sym)).first.length} " + query.formatted %></a>
        </h4>
        <div class="result-details">
          <table class="large-10 large-offset-1">
            <thead>
              <tr>
                <% if query == "crimes" %>
                  <th class="theader" width="150">Offense Type</th>
                  <th class="theader" width="100">Date Reported</th>
                <% else %>  
                  <th class="theader" width="150">Name</th>
                  <th class="theader" width="100">Distance From This Address</th>
                <% end %>
              </tr>
            </thead>
            <% @results.send(query.to_sym).first.map do |result| %>
              <%= render 'conditional_results', result: result, address: @first_address.address %>
            <% end %>
          </table>
        </div>
      </div>
    <% end %>
  </div>

  <div class="second-address-results large-6 columns">
    <% @queries.each do |query| %>
      <div class="results">
        <h4 class="small-4 small-centered columns">
          <a href="#" class="<%= "second-address-" + query %> criteria-details">
          <%= "#{(@results.send(query.to_sym)).last.length} " + query.formatted %></a>
        </h4>
        <div class="result-details">
          <table class="large-10 large-offset-1">
            <thead>
              <tr>
                <% if query == "crimes" %>
                  <th class="theader" width="150">Offense Type</th>
                  <th class="theader" width="100">Date Reported</th>
                <% else %>  
                  <th class="theader" width="150">Name</th>
                  <th class="theader" width="100">Distance From This Address</th>
                <% end %>
              </tr>
            </thead>
            <% @results.send(query.to_sym).last.map do |result| %>
              <%= render 'conditional_results', result: result, address: @second_address.address %>
            <% end %>
          </table>
        </div>
      </div>
    <% end %>
  </div>
    <div class="row">
  </div>
  <div class="email_popup">
    <div class="row email-inner">
      <button class="close-popup" href="javascript:void(0)"></button>
      <%= form_tag("/send-email", method: 'post') do%>
        <%= text_field_tag :user_email, nil, placeholder: "Enter email here to receive a copy of these results" %>
        <%= hidden_field_tag :results, @results %>
        <%= submit_tag "Send Results", class: "postfix" %>
      <% end %>
    </div>
  </div>
</div>
<div id="sticky_footer" class="text-center">
  <span><i class="fi-mail"></i>&nbsp
    <a href="#" class="footer-msg">Want a copy of these results?</a>&nbsp<i class="fi-mail"></i>
  </span>
</div>